WooriVeryGood/honeycourses-frontend

src/components/HomePage/HomePage.tsx
=> [HC-34-FE] 업데이트 내용 수정

src/components/Footer/Footer.tsx
=> [HC-32] Footer 날짜 수정

src/components/CommunityPostView/CommunityPostView.tsx, src/components/HomePage/HomePage.tsx
=> [HC-41] CommunityPostView 댓글 색깔 변경, HomePage 업데이트 내용 수정

src/components/AboutPage/AboutPage.module.css
AboutPage.module.css: WooriVeryGood 버튼 너비 폭 수정
=> [HC-49]About 페이지 WooriVeryGood 버튼 수정

src/components/Login/Login.tsx
[HC-46] Login.tsx 신입생들 위한 도움 메세지 작성
[HC-46]: https://honeycourses.atlassian.net/browse/HC-46?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HC-46 Login.tsx 신입생들 위한 도움 메세지 작성

src/components/CommunityHome/CommunityHome.tsx, src/components/HomePage/HomePage.tsx
- CommunityHome.tsx : 커뮤니티 카테고리별 분류 기능 추가
- HomePage.tsx : 업데이트 버전 추가
=> [HC-55] 커뮤니티 카테고리별 분류 기능 추가

src/components/CourseReviews/CourseReviews.tsx
CourseReviews.tsx: handleDownvote, handleUpvote 함수에 cognito token 없이 call해서 추천/비추 기능 자체가 마비되었었음. 수정 완료.
=> [HC-50] 강의평가 추천/비추 API Auth 누락 수정

src/components/AboutPage/AboutPage.module.css, src/components/CommunityHome/Community.module.css, src/components/CommunityHome/CommunityHome.tsx, src/components/CommunityPostView/CommunityPostView.css, src/components/CommunityPostView/CommunityPostView.tsx, src/components/CommunityPostView/communityPostView.module.css
CommunityHome.tsx: 카테고리, 포스트 테두리 등 수정
Community.module.css: CommunityHome을위한 css
CommunityPostView.tsx: 번호, 날짜시간 등 위치 수정, 댓글 형태 수정
communityPostView.module.css: communityPostView를 위한 css
CommunityPostView.css: 위와 동일
AboutPage.module.css: 폰트 수정으로 인한 오류 수정
=> [HC-51] 커뮤니티 UI 개선

src/App.tsx, src/components/Header/Header.tsx
- 1월 14일 현재 시점, 우선 dev 브랜치에 커뮤니티 기능 재활성화.
- App.tsx, Header.tsx : 커뮤니티 기능 숨김 해제
=> [HC-78] (FE) 커뮤니티 기능 재오픈

src/components/AddCourse/AddCourse.tsx, src/components/AddPost/AddPost.tsx, src/components/AddReview/AddReview.tsx
AddCourse.tsx, AddPost.tsx, AddReview.tsx : 중복 제출 확인하는 변수 추가
=> [HC-61] 중복 제출 수정

src/components/AddCourse/AddCourse.module.css, src/components/AddCourse/AddCourse.tsx, src/components/AddPost/AddPost.module.css, src/components/AddPost/AddPost.tsx, src/components/AddReview/AddReview.module.css, src/components/AddReview/AddReview.tsx, src/components/CommunityHome/Community.module.css, src/components/CommunityPostView/CommunityPostView.tsx, src/components/CommunityPostView/communityPostView.module.css, src/components/CourseList/CourseList.module.css, src/components/CourseReviews/CourseReviews.css, src/components/CourseReviews/CourseReviews.module.css, src/components/CourseReviews/CourseReviews.tsx
[HC-99] 강의 리뷰, 커뮤니티 글 카드 폭 조정
[HC-102] 수업 리스트 컴포넌트 검색 기능 폰트 수정
두 개 같이 함
AddCourse.tsx : AddCourse.module.css 임포트함.
AddCourse.module.css : 수업 추가 카드 폭 수정 및 폰트 추가
AddPost.tsx : AddPost.module.css 임포트 함.
AddPost.module.css : 커뮤니티 글 쓰기 카드 폭 조정 및 폰트 추가
AddReview.tsx : AddReview.module.css
AddReview.module.css : 리뷰 작성 카드 폭 수정 및 폰트 추가
Community.module.css : 커뮤니티 전체 폰트 추가
CommunityPostView.tsx , CommunityPostView.module.css : 커뮤니티 글 전체 폰트 추가
CourseList.module.css, CourseReview.module.css : 폰트 통일
** 폭 조정하면서 글 추가, 수업 추가, 리뷰 추가 제출 버튼 위치 모두 제자리를 찾음. 호진 오빠 일거리 하나 줄음.. **
[HC-99]: https://honeycourses.atlassian.net/browse/HC-99?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HC-102]: https://honeycourses.atlassian.net/browse/HC-102?atlOrigin=eyJpIjoiNWRkNTljN …
=> [HC-99-FE]  강의 리뷰, 커뮤니티 글 카드 폭 조정/ 수업 리스트 컴포넌트 검색 기능 폰트 수정

src/App.tsx, src/components/AddCourse/AddCourse.tsx, src/components/Header/Header.tsx
AddCourse.tsx : flexWrap:"nowrap" 추가해서 강의명 붕뜨는 오류 수정
App.tsx : 커뮤니티 부분 주석 지움
Header.tsx : 커뮤니티 부분 주석 지움
=> [HC-107] 강의 추가 페이지에 강의명 태그 오류 수정, 커뮤니티 다시 열기

.gitignore, amplify/.config/project-config.json, amplify/cli.json, amplify/team-provider-info.json, public/images/likeWhite.svg, src/components/AddCourse/AddCourse.tsx, src/components/AddReview/AddReview.tsx, src/components/CourseList/CourseList.tsx, src/components/CourseReviews/CourseReviews.tsx, src/components/HomePage/HomePage.tsx
=> [HC-116] 새 API 와 강의평가 기능 연동 완료

src/components/CommunityPostView/CommunityPostView.tsx, src/components/CommunityPostView/communityPostView.module.css
게시글 및 댓글을 불러올 수 있으며, 다음과 같은 기능도 구현했어요.
- 댓글 좋아요
- 게시글 좋아요
- 댓글 수정 및 삭제
- 버튼 반복 누르기 방지
- 게시글 수정 및 삭제
=> feature/community: 게시글 및 댓글 기능들 구현

src/components/CommunityPostView/CommunityPostView.css, src/components/CommunityPostView/CommunityPostView.tsx
하루를 갈아넣어서 만든 대댓글 기능.
- **CommunityPostView.css**: reply-arrow 추가하여 대댓글 표시 선명하게 보이도록 함.
- **CommunityPostView.tsx**: 변화사항이 엄청 많음.
1. 저자 닉네임, 배경 받아오는 로직 변경 (답글 생기면서 답글만 달고 댓글 안다는 사람은 원 로직대로면 Unknown으로 떴음)
2. 대댓글 보이도록 추가. 
3. 대댓글 추가/수정/삭제 기능 추가.
4. 대댓글이 있는 댓글 삭제시 삭제된 댓글이라 표시되게 변경.
=> [HC-133] 대댓글 기능 추가 완료

src/components/CourseReviews/CourseReviews.module.css, src/components/CourseReviews/CourseReviews.tsx
CourseReviews.module.css:
강의 리뷰 추천 버튼 커뮤니티 게시글 추천 버튼이랑 같은 스타일로 바꿈
CourseReviews.tsx:
강의 리뷰 추천 버튼 커뮤 버튼 처럼 바꿈
=> [HC-135]강의 리뷰 추천 버튼 바꾸기

src/components/CommunityHome/CommunityHome.tsx, src/components/CommunityPostView/CommunityPostView.tsx, src/components/CourseReviews/CourseReviews.tsx
CommunityHome.tsx:
커뮤니티 글 표시 시간 중국 시간으로 변경
CommunityPostView.tsx:
커뮤니티 글, 댓글, 답장 시간을 중국 시간으로 변경
날짜와 시간을 밀리초로 환산해서 8시간 더하고 다시 날짜와 시간으로 바꿈.
=> [HC-131]커뮤 글/댓글 표시 시간 로직 조정

src/components/Header/Header.tsx
Header.tsx:
Header에 더보기 버튼 칸 삐죽삐죽한 부분 수정
=> [HC-97]Header 컴포넌트 더보기 칸 수정

src/components/API/Headers.tsx, src/components/AddCourse/AddCourse.tsx, src/components/AddPost/AddPost.tsx, src/components/AddReview/AddReview.tsx, src/components/CommunityHome/CommunityHome.tsx, src/components/CommunityPostView/CommunityPostView.tsx, src/components/CourseList/CourseList.tsx, src/components/CourseReviews/CourseReviews.tsx, src/components/HomePage/HomePage.tsx
Headers.tsx:
headers부분 분리함
AddCourse.tsx:
기존 const headers 부분 삭제하고 새로 분리한 headers임포트해서 적용
AddPost.tsx:
기존 const headers 부분 삭제하고 새로 분리한 headers임포트해서 적용
AddReview.tsx:
기존 const headers 부분 삭제하고 새로 분리한 headers임포트해서 적용
CommunityHome.tsx:
기존 const headers 부분 삭제하고 새로 분리한 headers임포트해서 적용
CommunityPostView.tsx:
기존 const headers 부분 삭제하고 새로 분리한 headers임포트해서 적용
CourseList.tsx:
기존 const headers 부분 삭제하고 새로 분리한 headers임포트해서 적용
CourseReviews.tsx:
기존 const headers 부분 삭제하고 새로 분리한 headers임포트해서 적용
HomePage.tsx:
기존 const headers 부분 삭제하고 새로 분리한 headers임포트해서 적용
토큰을 
const jwtToken = sessionStorage.getItem("userInformation");
이렇게 해서 받았는데 setItem() 안했는데도 불러와져서 이게 왜되지? 싶었어요
이렇게 하는게 맞는지 잘모르겠숩니다.
=> [HC-144]API 콜 코드 분리

src/components/API/APIHandler.tsx, src/components/AddCourse/AddCourse.tsx, src/components/AddPost/AddPost.tsx, src/components/AddReview/AddReview.tsx, src/components/CommunityHome/CommunityHome.tsx, src/components/CommunityPostView/CommunityPostView.tsx, src/components/CourseList/CourseList.tsx, src/components/CourseReviews/CourseReviews.tsx, src/components/Footer/Footer.tsx, src/components/Header/Header.tsx, src/components/HomePage/HomePage.tsx, src/components/Login/Login.tsx
우리 컴포넌트들중 API와 통신이 필요한 코드들은 기본적으로 현재 유저의 Access Token을 받아서 header에 넣어서 API에 요청을 할 자격이 있다는 사용자임을 판별하기 위해 (API 보안) 아래와 비슷한 코드들이 있었습니다:
```typescript
import axios from "axios"; // API 콜을 하기 위한 라이브러리 import
import { Auth } from "aws-amplify"; // 유저 로그인 정보를 얻어오기 위한 import
const apiUrl = process.env.REACT_APP_API_URL; // API 주소, .env에서 설정한 값
const userSession = await Auth.currentSession();
const jwtToken = userSession.getAccessToken().getJwtToken();
const headers = {
Authorization: `Bearer ${jwtToken}`,
};
// 이상은 토큰을 받는 과정
```
하지만 이제 프로젝트 규모가 커져서 이런 코드가 필요한 컴포넌트가 한두개가 아니고, 매 컴포넌트를 새로 쓸때마다 이 코드를 다시 쓰니 컴포넌트마다 같은 일을 하는 코드들이 형식도 미묘하게 다르게 반복적으로 쓰이고 있었습니다. 
리팩토링의 핵심은 **중복되는 코드를 줄이는 것**입니다. 우리가 1학년때 函数를 괜히 배우는게 아니죠. 이번에 드디어 API 콜 관련 리팩토링을 진행했습니다.
핵심 코드인 ```APIHandler.tsx```의 3가지 함수를 살펴봅시다.
``` …
```
=> [HC-144] API 콜 관련 코드 리팩토링 완료

src/components/AddReview/AddReview.tsx, src/components/CourseReviews/CourseReviews.tsx
- AddReview.tsx: 리팩토링 덜된 부분 보여서 수정
- CourseReviews.tsx: 내용/제목 외에도 수강 학기, 교수명, 성적도 수정 가능하게 변경. 수정 완료후 더보기의 수정/삭제 버튼이 여전히 열려있던 문제도 해결.
=> [HC-148] 강의평가 제목/내용 외도 수정 가능하게 변경

src/components/CourseList/CourseList.tsx
- CourseList.tsx: 강의 목록에 해당 강의의 리뷰 갯수가 보이도록 뱃지 추가. 추후 색 수정 가능.
=> [HC-149] 강의 목록에 강의 평가 갯수 보이도록 추가

src/components/CommunityPostView/CommunityPostView.tsx, src/components/CourseList/CourseList.tsx, src/components/CourseReviews/CourseReviews.module.css, src/components/CourseReviews/CourseReviews.tsx
- CommunityPostView.tsx: 데이터 요청에 Promise 사용, 존재하지 않는 게시물에 대한 처리 추가
- CourseList.tsx: 강의를 선택하면 새로운 탭에서 열리도록 변경
- CourseReviews.module.css: 리뷰 ID, 작성일자 스타일 추가
- CourseReviews.tsx: 존재하지 않는 강의 처리 로직 수정, 강의리뷰 ID 보이게 추가, 작성일자가 없는 이전 리뷰들은 그냥 일자를 비워두도록 수정 (길어지면 모바일에서 못생겨짐)
커뮤니티의 경우 페이지네이션이 적용되어 강의평가같은 문제가 없으니 새 탭에서 열리게 적용 안함.
=> [HC-42] 강의평가 새로운 탭에서 열리도록 변경, 존재하지 않는 게시물 처리 추가 등

src/components/AddCourse/AddCourse.tsx, src/components/AddPost/AddPost.tsx, src/components/AddReview/AddReview.tsx, src/components/CommunityPostView/CommunityPostView.tsx, src/components/CourseReviews/CourseReviews.tsx
CommunityPostView.tsx:
커뮤니티 게시글/ 댓글 수정시 수정됨 표시
CourseReviews.tsx:
강의 평가 수정시 수정됨 표시
AddCourse.tsx:
중복 제출되지 않기위해 쓴 if문 준우오빠 코드 참고해서 간결하게 바꿈
AddPost.tsx:
중복 제출 방지 if문 간결하게 바꿈
AddReview.tsx:
중복 제출 방지 if문 간결하게 바꿈
=> [HC-141]커뮤니티 게시글/댓글, 강의 평가 수정 여부 표시

src/components/Paging/Paging.css
Paging.css:
폰트 추가, 폰트 사이즈 굵기 변경, 색상 변경
=> [HC-145]페이지네이션 UI 수정

amplify/backend/analytics/honeycoursesfrontend/parameters.json, amplify/backend/analytics/honeycoursesfrontend/pinpoint-cloudformation-template.json, amplify/backend/auth/honeycoursesfrontend/cli-inputs.json, amplify/backend/backend-config.json, amplify/backend/types/amplify-dependent-resources-ref.d.ts, amplify/team-provider-info.json, src/components/Header/Header.tsx, src/components/HomePage/HomePage.tsx
- Ampify Analytics 추가되어서 방문자 수, 트래픽 등 통계 가능해짐
- 성적조회 링크 Header에 추가, 홈페이지 커뮤니티 베타 서비스 종료배너 제거
=> [HC-17] Ampify Analytics 추가, 성적조회 링크 추가

src/App.tsx, src/components/Header/Header.tsx, src/components/MyInfo/MyInfo.module.css, src/components/MyInfo/MyInfo.tsx
- App.tsx: 비밀번호 변경 UI 한국어 번역 추가, myinfo 컴포넌트 루트 추가
- Header.tsx: 내 정보 버튼 추가
- MyInfo.tsx, MyInfo.module.css: 내 정보 컴포넌트 추가
내 정보, 리뷰, 게시글 확인 가능
=> [HC-121] 내 정보 페이지 추가

src/components/Support/Support.module.css, src/components/Support/Support.tsx
Support.tsx:
카드 애니메이션 삭제, 버튼 추가
Support.module.css:
Support us 페이지 버튼 추가, 반응형
=> [HC-95]Support us! 페이지 수정

src/components/CommunityHome/CommunityHome.tsx, src/components/CommunityPostView/CommunityPostView.tsx, src/components/MyInfo/MyInfo.tsx
- CommunityHome.tsx: 신고 누적 처리된글 제목과 내용 처리
- CommunityPostView.tsx: 글, 댓글 신고 처리 로직 추가, 신고 누적 처리된글 제목과 내용, 댓글과 답글 내용 처리, 신고버튼 추가
=> [HC-160] 글, 댓글 신고 추가

src/components/CommunityPostView/CommunityPostView.tsx
- CommunityPostView.tsx: 52명의 다른 댓글 사용자 수용하도록 닉네임 확장
=> [HC-136] 52명의 다른 댓글 사용자 수용하도록 닉네임 확장

src/pages/CourseList/CourseList.module.css, src/pages/CourseList/components/CourseSidebar/CourseSidebar.module.css, src/pages/CourseList/components/MajorSelector/MajorSelector.tsx
- CourseList.module.css -> CourseSidebar.module.css: 사이드바 모바일 미디어쿼리 누락, 이동하여 수정
- MajorSelector.tsx: 주석 수정
=> Fix: CourseList 사이드바 모바일 css 누락 수정

package.json, src/App.tsx, src/components/Loader/Loader.tsx, src/pages/API/APIHandler.tsx, src/pages/API/courses/CourseApi.ts, src/pages/API/courses/useCourses.ts, src/pages/CourseList/CourseList.tsx, src/pages/CourseList/components/CourseCard/CourseCard.tsx, yarn.lock
- 프로젝트에 React-query 초기 도입 완료
- Courselist에 강의목록 받아올시 리액트 쿼리 사용, staleTime 5분으로 설정
- React-query가 자동으로 스크롤 복원을 지원하는 관계로 원래 있던 스크롤 복원 로직 삭제
=> [HC-190] React-query셋업, Courselist 초기 도입

src/API/reviews/useAddReview.ts, src/API/reviews/useReviews.ts, src/pages/CourseReviews/CourseReviews.tsx
- 마지막 리뷰 작성 이후 6개월 초과시 리뷰 열람이 불가하도록 수정
=> [HC-202] 마지막 리뷰 작성 6개월 초과시 열람권한 조정

index.html, src/index.css, src/pages/AboutPage/AboutPage.module.css, src/pages/MyInfo/MyInfo.module.css, src/pages/Support/Support.module.css
원래 눈누라는 폰트 다운받는 사이트에서 끌어왔는데 아마 그 링크에 문제가 있었던 것으로 추측 그래서 네이버 글꼴 모음 사이트에서 똑같은 나눔스퀘어 네오 폰트 링크로 바꿨습니다
index.css:
폰트 이름 NanumSquareNeo-Variable에서 NanumSquareNeo으로 변경, 폰트 다운받는 경로 변경
AboutPage.module.css:
폰트 이름 수정
MyInfo.module.css:
폰트 이름 수정
Support.module.css:
폰트 이름 수정
=> [HC-207] 폰트 오류 수정

src/pages/CommunityPostView/components/CommentList/index.tsx, src/pages/CommunityPostView/index.tsx, src/types/comment.d.ts, src/types/post.d.ts
comment.ts:
댓글 타입 변수 이름 변경
post.ts:
커뮤니티 게스글 타입 변수 이름 변경
index.tsx (게스글):
변수 이름 변경
index.tsx:
변수 이름 변경
=> [FE] 커뮤니티 게시글, 댓글 타입 변수 이름 변경 완료

src/pages/AddCourse/components/AddCourseForm.tsx
AddCourseForm.tsx: 새 강의추가시 강의 카테고리가 体育课，英语课 일때 开课院系 자동으로 해당 院系로 설정하도록 수정
=> [HC-33] 새 강의추가시 강의 카테고리가 体育课，英语课 일때 开课院系 자동설정

package.json, src/pages/CommunityPostView/components/CommentListItem/components/CommentContent.tsx, src/pages/CommunityPostView/components/PostContainer/index.tsx, src/pages/CommunityPostView/components/ReplyListItem/components/ReplyContent.tsx, src/pages/CourseReviews/components/ReviewCard/ReviewCard.tsx, yarn.lock
package.json: url 인식을위해 linkifyjs 모듈 다운받음
CommentContent.tsx: 댓글 url 인식
index.tsx(PostContainer): 커뮤니티 글 url 인식
ReplyContent.tsx: 답글 url 인식
ReviewCard.tsx: 강의평가 url 인식
=> [HC-163] 강의평가, 커뮤니티 글, 댓글에 url 인식할 수 있도록 수정함

src/pages/AboutPage/AboutPage.module.css, src/pages/AboutPage/AboutPage.tsx, src/pages/AboutPage/components/AboutSection/AboutSection.module.css, src/pages/AboutPage/components/AboutSection/AboutSection.tsx
AboutPage.tsx: AboutPage 디자인 병경
AboutSection.tsx: 텍스트와 버튼 컴포넌트 생성
=> [about-page-redesign] about 페이지 디자인 바꿈

src/pages/AddReview/AddReview.tsx
AddReview.tsx: 신입생들이 신입생 게시판에 리뷰를 작성하여 다른 리뷰들을 열람할수 있도록함.
=> [freshman-board] 강의평가에 신입생 게시판 추가
